json-server:
	./node_modules/.bin/env-cmd -f .env.local --use-shell "npm run json-server"

local:
	./node_modules/.bin/env-cmd -f .env.local --use-shell "npm start"

story-book:
		npm run storybook

dev:
	./node_modules/.bin/env-cmd -f .env.development --use-shell "npm install && npm run build"

production:
	./node_modules/.bin/env-cmd -f .env.production --use-shell "npm install --production && npm run build"
