name: create-wish-work-app
on:
  push:
    branches: [master, main]
    pull_request: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run the tests
        run: npm run test
      - name: Build
        run: npm run build --if-present
      - name: Deploy
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          make github
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          github_url: ${{ secrets.REACT_APP_GITHUB_URL }}
          repository: ${{ github.repository }}

